remote_theme: b2a3e8/jekyll-theme-console

title: 'Yaoxins Tech Blog'

style: light

header_pages:
  - index.md
  - Book.md
  - C.md
  - C++.md
  - Unix.md
  - OOP.md
  - Algorithm.md
  - SQL.md
  - About.md
  
footer: 'Yaoxin.'
